version: '3.8'

services: 
  web: 
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      
  redis:
    image: redis:alpine
  
  celery:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - ./app:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web
    
  celery-beat:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - ./app:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web


volumes: 
  postgres_data:
#To persist the data beyond the life of the container we configured a volume. 
#This config will bind postgres_data to the "/var/lib/postgresql/data/" 
#directory in the container.
