version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    # Now, port 8000 is only exposed internally, to other Docker services. 
    # The port will no longer be published to the host machine. (after adding nginx conf)
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - redis
      - web

  redis:
    image: redis:alpine

  celery:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - .:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web
    
  celery-beat:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - .:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

# add a volume to the web and nginx services in docker-compose.prod.yml 
# so that each container will share a directory named "staticfiles"